# Generated by Django 4.1 on 2022-12-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideKAMI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masukan', models.TextField()),
            ],
        ),
    ]
