# Generated by Django 4.1 on 2022-12-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideKAMI', '0002_aspirasi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Masukan',
        ),
    ]
